export const GET_DATA = 'GET_DATA';
export const FILTERS = 'FILTERS';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_PRODUCTS_ITEMS = 'UPDATE_PRODUCTS_ITEMS';